// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package api

import (
	"encoding/json"

	"github.com/ethereum/go-ethereum/common/hexutil"
)

var _ = (*getHeaderResponseMarshalling)(nil)

// MarshalJSON marshals as JSON.
func (g GetHeaderResponse) MarshalJSON() ([]byte, error) {
	type GetHeaderResponse struct {
		Message   GetHeaderResponseMessage `json:"message"`
		Signature hexutil.Bytes            `json:"signature"`
	}
	var enc GetHeaderResponse
	enc.Message = g.Message
	enc.Signature = g.Signature
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (g *GetHeaderResponse) UnmarshalJSON(input []byte) error {
	type GetHeaderResponse struct {
		Message   *GetHeaderResponseMessage `json:"message"`
		Signature *hexutil.Bytes            `json:"signature"`
	}
	var dec GetHeaderResponse
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Message != nil {
		g.Message = *dec.Message
	}
	if dec.Signature != nil {
		g.Signature = *dec.Signature
	}
	return nil
}
